unlock GNOME session for RDP

diff --git a/home/dot_zshrc.tmpl b/home/dot_zshrc.tmpl
--- a/home/dot_zshrc.tmpl
+++ b/home/dot_zshrc.tmpl
@@ -187,6 +187,20 @@ alias manp=man-preview
 
 # macOS: Enable additional iTerm2 support
 [[ ! -f ~/.iterm2_shell_integration.zsh ]] || source ~/.iterm2_shell_integration.zsh
+
+{{- else if eq .chezmoi.os "linux" }}
+
+# Unlock seat0 for remote RDP to GNOME
+function unlock () {
+    seat=${1:-seat0}
+    session=$(loginctl list-sessions | awk -v pattern="${seat}" '$0 ~ pattern { print $1 }')
+    if [[ -z "${session}" ]]; then
+        echo "loginctl session not found for seat ${seat}!" >&2
+        loginctl list-sessions
+        return 1
+    fi
+    loginctl unlock-session ${session}
+}
 {{- end }}
 
 ############  Dev Stuff here  ############
