Upate to newer version of asdf
Later versions rewritten in go have breaking changes
and are installed differently.

diff --git a/home/.chezmoiscripts/run_onchange_after_90-configure-asdf.sh.tmpl b/home/.chezmoiscripts/run_onchange_after_90-configure-asdf.sh.tmpl
--- a/home/.chezmoiscripts/run_onchange_after_90-configure-asdf.sh.tmpl
+++ b/home/.chezmoiscripts/run_onchange_after_90-configure-asdf.sh.tmpl
@@ -5,9 +5,12 @@
 
 set -eufo pipefail
 
-source "$HOME/.asdf/asdf.sh"
+if ! command -v asdf >/dev/null ; then
+    echo "$0: WARNING: asdf not found" >&2
+    exit
+fi
 
-asdf plugin-add kubectl https://github.com/asdf-community/asdf-kubectl.git
+asdf plugin add kubectl https://github.com/asdf-community/asdf-kubectl.git
 asdf install kubectl latest
 
 {{ end -}}
